-- Track whether products.description_en was written by AI or typed manually by Sam.
--
-- Why: the app previously could not distinguish an AI-generated bio from one Sam
-- wrote herself, so "Amend AI analysis" silently overwrote hand-written text.
-- With this column, a manual description is protected unless she explicitly opts in.
--
-- Values:
--   'ai'      — generated by intake analysis or Regenerate Bio
--   'manual'  — typed or cleared by Sam in the bio editor
--   NULL      — legacy row written before this column existed; treated as 'ai'
--
-- Non-destructive: adds a nullable column, changes no existing data.

ALTER TABLE products
ADD COLUMN IF NOT EXISTS description_source TEXT;

ALTER TABLE products
DROP CONSTRAINT IF EXISTS products_description_source_check;

ALTER TABLE products
ADD CONSTRAINT products_description_source_check
CHECK (description_source IS NULL OR description_source IN ('ai', 'manual'));
